version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: traffic_qdrant
    ports:
      - "6334:6333"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  traffic_rag_app:
    build:
      context: ..
      dockerfile: traffic_rag/Dockerfile
    container_name: traffic_rag_backend
    ports:
      - "8003:8000"
    env_file:
      - ../.env
    depends_on:
      - qdrant
    volumes:
      - ..:/app
